### ISSUE TITLE
Only supports v3.3

### ISSUE THREAD

**Issue by andyallan** [graylog-labs/graylog-plugin-pagerduty#19]
I noticed that the docs claim the updated plugin supports v3.1 and later.

From testing both 3.1 and 3.2, the "PagerDuty Notification" type never appears when creating a new notification.

It's only available on v3.3+

At the very least the docs need updated, but if the intention was indeed for 3.1 and upwards to be supported, a wee bit extra digging will be required.

**Comment by cameronattard** [comment]
Would be good to get some clarification on this. I'd like to use the plugin but don't want to use the 3.2+ UI.

**Comment by andyallan** [comment]
The docs have been updated to confirm that support is for 3.3+.

@waab76 also confirmed this to me on Twitter. 

I'm going to close this off as the question of version support has been answered.
